# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee2a53e4307a6695ae7372a2092814f1085e31605b4d768f5112937068eb4ce00cd427e9c469c96de947e327c7874723f3ba328274f70fc64e0c5a3bccbad614

test:
  secret_key_base: 74c9de940b052d2d5fb5904ab1d7d8e16be928fc7bd12adab6663fa35b5543fdfc5f03777b3548dd26e54fff23f0f3cab3d42bd1f11536e013648a43c7623aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
